### ISSUE TITLE
TCI contribution

### ISSUE THREAD

**Issue by shyiam81** [TIBCOSoftware/tci-awesome#11]
Title: Alexa skill template for Flogo
Color: Green
Description: This Flogo JSON file, once uploaded to TIBCO Cloud Integration, will provide you a template for building a service that receives Alexa requests, performs a set of actions that you define, and then send the appropriate response for Alexa to respond to the end-user. 
URL: https://github.com/shyiam81/TCI_Flogo/blob/master/Alexa_Skill_Flogo.json

**Comment by rishikeshpalve** [comment]
Thanks @shyiam81 for sharing your contribution. It is now added to our showcase at https://tibcosoftware.github.io/tci-awesome/
