### ISSUE TITLE
List Flogo activity for json2xml

### ISSUE THREAD

**Issue by d-sauer** [TIBCOSoftware/tci-awesome#14]
Dear, 
if possible I would like to contribute to the Flogo.io Showcase with the following Flogo activity:
```
title: Json2XML
color: green
description: Activity for converting JSON object into XML
url: https://github.com/d-sauer/contrib/tree/master/activity/json2xml
```

Kind regards,
Davor

**Comment by vijaynalawade** [comment]
@d-sauer Please create PR by adding above in https://github.com/TIBCOSoftware/tci-awesome/blob/master/docs/data/items.toml

**Comment by d-sauer** [comment]
Perfect, thx for the advice.

**Comment by d-sauer** [comment]
PR created https://github.com/TIBCOSoftware/tci-awesome/pull/15
