### ISSUE TITLE
Tibco Utilities Palettes

### ISSUE THREAD

**Issue by surfra** [TIBCOSoftware/tci-awesome#5]
DESCRIPTION: 
HI, I'm Francesco Suraci, I developed some projects for all developers that work with Tibco's product (Business Works, Business Studio, Designer...).
--- Tibco Utilities ---
Tibco Utilities contains a plugin with 2 new palettes:
GetToken
IpFilter

 GetToken -
is useful to get the authentication token and then connect to the server and make the calls.
It also manages retries, in order to make more calls in case of failure of the previous call.

IpFilter -
is useful to check the IP address that is making the call and check if it is on the white list of allowed and valid IPs. This is to prevent calls from unknown or invalid external IP addresses.

URL :  https://github.com/surfra/Tibco/wiki/Francesco-Suraci

HEX color: 288FBD

**Comment by rishikeshpalve** [comment]
Thanks @surfra for your contribution :) We'll review it and list it on the showcase.

**Comment by rishikeshpalve** [comment]
Hi @surfra your contribution is now listed on TCI Showcase as well as included in the list on tci-awesome GitHub repo. You can check the showcase at - https://tibcosoftware.github.io/tci-awesome/

**Comment by surfra** [comment]
Hi,
thanks!
